### ISSUE TITLE
Support for debug builds with cmake

### ISSUE THREAD

**Issue by maximiliank** [CodeAvailable/conan-xlnt#2]
I am using conan together with CMake and when building in debug mode the xlnt library (1.5.0) is created with debug postfix, since it is set in xlnt's cmake file:
`set(CMAKE_DEBUG_POSTFIX "d" CACHE STRING "Set debug library postfix")`

So the generated library is named `libxlntd.a`. Unfortunately it tries to link with `-lxlnt` which is of course not found by the linker.

If I run conan with `BUILD_TYPE "Release"` (https://github.com/conan-io/cmake-conan#build_type) it uses always the relase version and the linking works.

Would it be possible to handle the debug postfix in the recipe similar to the gtest recipe (https://conan.io/center/gtest?tab=recipe)?

**Comment by shajeen** [comment]
Hi,
Support for Debug has been added. Please give it a try.

**Comment by maximiliank** [comment]
Works great. Thank you!
